### ISSUE TITLE
dashboard 케러셀 추가 및 이미지 추가, 각 space별 이미지 추가

### ISSUE THREAD

**Issue by yeolsss** [yeolsss/nbc-nep#63]
![Screen Shot 2024-01-25 at 3 34 54 PM](https://github.com/yeolsss/nbc-nep/assets/33962538/4f4f96d7-ef42-41a6-8130-fe904386ce7d)

**Comment by dygmm4288** [comment]
![image](https://github.com/yeolsss/nbc-nep/assets/55860930/9e487755-63b8-44b7-bd80-e23c2081d879)
![image](https://github.com/yeolsss/nbc-nep/assets/55860930/c1ff2f83-ce4a-41aa-9a71-12ce11747762)
![image](https://github.com/yeolsss/nbc-nep/assets/55860930/860918d0-36e5-4306-bd88-c35ef21a8875)
![image](https://github.com/yeolsss/nbc-nep/assets/55860930/2db9b823-c05a-480c-8e43-a7ad64d68d79)
레터 좀 넣고 가독성 고려 description 폰트 바꾸기
![image](https://github.com/yeolsss/nbc-nep/assets/55860930/05ba962a-1106-4855-9f81-efbbf10ee23d)
20글자까지는 늘려도 될 것 같음
![image](https://github.com/yeolsss/nbc-nep/assets/55860930/7d68a1f1-061a-4bee-8472-c488895a2c69)
배너 이미지 순서

**Comment by dygmm4288** [comment]
완료했슴다
