### ISSUE TITLE
20240126 버그 및 UI/UX 체크 

### ISSUE THREAD

**Issue by kms99** [yeolsss/nbc-nep#73]
**로그인**
- [x] 1. 미들웨어 확인 요망 
	- [x]  비로그인 시 dashboard 접근 가능
- [x] #77 (회원가입시 바로 홈으로 리디렉션 추가)
---------------------------------------------

**소개페이지**
- [ ] 1. space 내부 기능 소개페이지에서 설명
---------------------------------------------

**대시보드**
- [x] 1. 스페이스 생성 아바타 프리뷰 같이 변경되도록 필요

- [x] #75
	- [x]  validation check message 개선 필요
	- [x]  하단 button 레이아웃 개선 필요
 	
- [x] 3. 배너를 통해 입장한 스페이스는 다시 배너를 통해 입장하려 시도할 때 막아야함.
---------------------------------------------

**스페이스**
- [x] #74
	- [x]  GNB Chat 2뎁스 네임 고민 필요
	- [x]  스페이스 내부 DM 레이아웃 확인 필요
- [x] 3. GNB 
	- [x] #80
	- [x]  GNB 맨 아래 버튼 기능 헷갈립니다. (아이콘 이슈)
- [x] 4. 레이아웃
	- [x]  화면 공유 레이아웃 활성화 시 하단 독 opacity 필요
	- [x]  레이아웃 지정 문구 변경 (맥 유저 고려)
	- [x]  레이아웃 프리뷰 상단 마진 필요
	- [x]  레이아웃 버튼 닫기 붉은색으로
- [x] 5. 우측 영상/화상 공유 레이아웃 스크롤바 제거 필요
- [x] 6. 하단 독 닉네임 부분 호버 색상 변경 부탁드립니다.

**Comment by dygmm4288** [comment]
- [ ] 화면 공유 시 스택 swiper 적용

**Comment by dygmm4288** [comment]
- [ ] metaverse에서 튕기면 초대 코드 입장하기 form 계속 생성돼 있음(버그)
- [ ] 긴글은 breakdown  css 이슈

**Comment by kms99** [comment]
GNB TODO
- [ ] player list 열릴 때 줄바뀜 현상  
- [ ] DM
  - [ ] 디자인 수정
  - [ ] Chat 발생 시 소리 내기
